spring.application.name=Order-Demo
server.port=8080


# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true

# Circuit Breaker
resilience4j.circuitbreaker.instances.payment-demo.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.payment-demo.sliding-window-size=5
resilience4j.circuitbreaker.instances.payment-demo.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.payment-demo.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.payment-demo.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.payment-demo.permitted-number-of-calls-in-half-open-state=2

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.circuitbreaker.enabled=true